### PR TITLE
SPRXCLT-4 fix request gets aborted

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by nicolas2bert** [comment]
ping

**Review by miniscruff — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert approve

**Comment by nicolas2bert** [comment]
@bert-e wait

**Review by jonathan-gramain — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
Superseded by https://github.com/scality/sproxydclient/pull/290

**Pull request closed without merging**
