### PR TITLE
FT: allow to add HTTP headers to getHEAD request

### PR DESCRIPTION
**Pull request by ThibaultRiviere**

### CODE REVIEW

**Review by LaurenSpiegel — APPROVED** [review]

**Review by alexandre-merle — APPROVED** [review]
LGTM

**Comment by alexandre-merle** [comment]
@ironman-machine did you work ?

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ghost** [comment]
Not 100% backwards compatible (providing headers undefined will lead to providing an option object that we've never provided before).
As this was never a PM-driven change and there is thus no neccesity for it, closing down.

**Pull request closed without merging**
