### PR TITLE
FT: Node v4.5.0 and new buffer api switch

### PR DESCRIPTION
**Pull request by alexandre-merle**
Update to the new buffer api

### CODE REVIEW

**Comment by alexandre-merle** [comment]
@ironman-machine let's go
SCALITY_INTEGRATION_BRANCH=fix/nimrod-build-dep
SCALITY_FEDERATION_BRANCH=ft/dep-patcher-ansible

**Comment by LaurenSpiegel** [comment]
@alexandre-merle, looks like end to end failed?

**Comment by alexandre-merle** [comment]
@ironman-machine without flaky test :)
SCALITY_INTEGRATION_BRANCH=fix/nimrod-build-dep
SCALITY_FEDERATION_BRANCH=ft/dep-patcher-ansible

**Comment by rahulreddy** [comment]
@ironman-machine again
SCALITY_INTEGRATION_BRANCH=fix/nimrod-build-dep
SCALITY_FEDERATION_BRANCH=ft/dep-patcher-ansible

**Comment by alexandre-merle** [comment]
end to end passed :)

**Pull request merged**
