### PR TITLE
ARTESCA-9178: make the agentkeepalive configurable or disable-able

### PR DESCRIPTION
**Pull request by ghost**
Testing only, for a client.

## Not meant to be merged. Please use a proper sproxyd jira ticket

### CODE REVIEW

**Review by fmonjalet — APPROVED** [review]

**Comment by fmonjalet** [comment]
I think it can be helpful to keep these tunables (not only for tests or CNES), I just wonder about the names and the practices around that. Maybe @jonathan-gramain or @francoisferrand will have visibility on that.

**Review by francoisferrand — APPROVED** [review]
Code and flag names look ok AFACT.

Generally, I am not really in favor of introducing such tunables: seems like debugging flags, which will be seldom used and should not be used in prod, so may not be worth the extra code/maintenance. Another way of seeing it: this path leads to introducing 100s of options, to make debugging easy in "all" situations but would make maintenance a headache...

Now maybe this is really needed in this specific case, not really sure : so please share your reasoning in this specific case, and maybe @nicolas2bert or @jonathan-gramain can chip in as well.

**Comment by ghost** [comment]
Hello @fmonjalet @francoisferrand , please reopen a new PR with a proper Jira project if this is to be merged; for now, this was only there for testing in case it was helpful to debug the client issue, it was never meant to be in the product. Today the ability to control the socket numbers is possible but not persistent, it should be in the Zenko CR. We have a troubleshooting documentation on that, but it is overriden everytime ZKOP reconciles. About the other ones (free socket timeout + socket timeout), it should also be configurable from the Zenko CR, not with process.env. Then we can pas the config through the client configuration when creating it.

**Comment by francoisferrand** [comment]
> Hello @fmonjalet @francoisferrand , please reopen a new PR with a proper Jira project if this is to be merged; for now, this was only there for testing in case it was helpful to debug the client issue, it was never meant to be in the product.

@williamlardier so we should close this PR already, right?

**Pull request closed without merging**
