### PR TITLE
Treat 423 responses on DELETEs as success

### LINKED ISSUE #111: Sproxyd 423 status codes could be treated as success
We return 500 currently.

### PR DESCRIPTION
**Pull request by RachedBenMustapha**
Concurrent deletes on sproxyd return 423 Locked.

Fix #111

### CODE REVIEW

**Comment by RachedBenMustapha** [comment]
@ironman-machine try

**Comment by RachedBenMustapha** [comment]
Yes, the s3 client itself is issuing multiple DELETEs so we let s3 return 200/204 during the few milliseconds that has the object still in metadata but already deleted in sproxyd.

**Comment by ThibaultRiviere** [comment]
But if an error happens we will respond 200 ? It's not a problem ?

**Comment by RachedBenMustapha** [comment]
@ThibaultRiviere 423 is returned by sproxyd on DELETE only when it has already been deleted (because it's immutable and not purged by the RING yet) so I don't see which error condition you're referring to.

**Comment by ThibaultRiviere** [comment]
@RachedBenMustapha i didn't know that the lock begin after the deletion .
So indeed if it is after i have no reason to worry thanks for the explanation .

**Comment by ThibaultRiviere** [comment]
@RachedBenMustapha An other question. If it's a put does sproxyd lock too ?

**Comment by RachedBenMustapha** [comment]
@ThibaultRiviere yes sproxyd locks objects on PUT, so if we try to delete them at the same time we'll get 423. But in practice it's not possible that s3 tries delete these objects while they are still being put, because their keys will not have been written to metadata and thus a DELETE on that object would say 404 directly from s3 and would not reach sproxydclient.

**Comment by rahulreddy** [comment]
@ThibaultRiviere GTG?

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@RachedBenMustapha @rahulreddy In this case go ahead guys

**Pull request merged**
